### ISSUE TITLE
1.8.10b not displaying on rift 0.8

### ISSUE THREAD

**Issue by wtfiAndrewNelson** [cmbruns/gz3doom#113] opened 2016-04-08 14:45 UTC
The mirror displays the game fine and the sensors are working on the mirror but the DK1 has a black screen with no game display.

**Comment by cmbruns-hhmi** [comment] 2016-04-08 14:51
Do versions of GZ3Doom older than 1.8.10b work for you on the DK1?

**Comment by wtfiAndrewNelson** [comment] 2016-04-08 23:31
After many frustrating hours, I gave up on my "main" system and tried things on one of my other computers... It seems to be working fine and I seem to be having other problems on the first computer so, I'm going to do a clean windows install and try again. Thanks for getting back to me, and I'm sorry for wasting your time.Date: Fri, 8 Apr 2016 07:51:44 -0700

**Comment by cmbruns** [comment] 2016-04-08 23:58
Sounds like this might have been a one time thing. Until someone can reproduce this problem, I'm closing this issue.
By the way. of course versions of GZ3Doom 1.8.10_c and later won't work with DK1, because OVR SDK 1.3 does not work with DK1.

**Closed by cmbruns** 2016-04-08 23:58 UTC
